export default {
  LOAD_SECTIONS_REQUEST : 'LOAD_SECTIONS_REQUEST',
  LOAD_SECTIONS_SUCCESS : 'LOAD_SECTIONS_SUCCESS',
  LOAD_SECTIONS_FAILED : 'LOAD_SECTIONS_FAILED',
  ADD_SECTION_SUCCESS : 'ADD_SECTION_SUCCESS',
  ADD_SECTION_REQUEST : 'ADD_SECTION_REQUEST',
  ADD_SECTION_FAILED : 'ADD_SECTION_FAILED',
  CREATE_TODO_REQUEST: 'CREATE_TODO_REQUEST',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILED: 'CREATE_TODO_FAILED'
}